version: '3.3'

services:
    db:
    image: mysql:5.7
    restart: always
    environment:
          MYSQL_ROOT_PASSWORD: wordpressdb
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
    volumes:
      - ./mysql:/var/lib/mysql



    
    wordpress:
        depends_on:
            -db
        image: wordpress:latest
        restart: always
        ports:
          - "8000:80"
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_NAME: wordpress
